---
- name: Install dependencies for PPA
  apt:
    name: 
      - software-properties-common
      - python3-launchpadlib
    state: present

- name: Preseed iptables-persistent answers
  debconf:
    name: iptables-persistent
    question: "{{ item }}"
    value: 'true'
    vtype: 'boolean'
  loop:
    - iptables-persistent/autosave_v4
    - iptables-persistent/autosave_v6

- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: Add AmneziaWG PPA
  apt_repository:
    repo: 'ppa:amnezia/ppa'
    state: present

- name: Install AmneziaWG packages
  apt:
    name:
      - amneziawg
      - amneziawg-tools
    state: present
    update_cache: yes