"""add subscription fields to users

Revision ID: 23f36772d881
Revises: 9fef9a27cd24
Create Date: 2026-05-26 14:49:10.098936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f36772d881'
down_revision: Union[str, Sequence[str], None] = '9fef9a27cd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_subscribed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('peer_ip', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('subscribed_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribed_until')
    op.drop_column('users', 'peer_ip')
    op.drop_column('users', 'is_subscribed')
    # ### end Alembic commands ###
