---
new_user: vpnadmin
ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

ufw_allowed_ports:
  - "22/tcp"
  - "443/tcp"

xray_inbound_port: 443
xray_log_level: warning
xray_dest: "www.microsoft.com:443"
xray_server_name: "www.microsoft.com"
xray_fingerprint: chrome
xray_short_id: "6ba85179e30d4fc2"

monitoring_dir: /opt/monitoring
grafana_port: 3000
prometheus_port: 9090
loki_port: 3100
grafana_admin_password: "changeme"
prometheus_retention: "30d"

moldova_entry_ip: "45.140.146.134"
